### ISSUE TITLE
How do I load this so as a vulkan layer without it crashing?

### ISSUE THREAD

**Issue by NadeemSadiq** [exellian/vulkan-layer-rs#1]
Before anything, great to see this template and I do appreciate it.

I pulled it down and built but and tried to link pre load it via LD_PRELOAD where i set the path to the .so file.

How ever, this does not seem to work. I put in println messages and expect the log messages to show up but i sadly see nothing show up.

I can see in the LD_DEBUG that the .so file did load up. Though, I am a little new to all this so I am probably missing something somewhere.

**Comment by NadeemSadiq** [comment]
I solved the issue where its not loading correctly. I ran `vulkaninfo | grep wsi` and saw that for some reason on my system, it could not be loaded unless `disable_environment` was added to the `wsi.json`. So I added `disable_environment` and `enable_environment`. It now loading correctly but I does seem to crash out. Will continue to investigate.

The error i am getting now is the following when running `vkcube` with the wsi vulkan layer

```
[wsi] Get instance proc: vkCreateInstance
[wsi] Creating instance!
[wsi] Got chain info!
[wsi] Created instance!
[wsi] Get instance proc: vkDestroyInstance
[wsi] Get instance proc: vkEnumeratePhysicalDevices
[wsi] Get instance proc: vkGetPhysicalDeviceFeatures
[wsi] Get instance proc: vkGetPhysicalDeviceFormatProperties
[wsi] Get instance proc: vkGetPhysicalDeviceImageFormatProperties
[wsi] Get instance proc: vkGetPhysicalDeviceProperties
[wsi] Get instance proc: vkGetPhysicalDeviceQueueFamilyProperties
[wsi] Get instance proc: vkGetPhysicalDeviceMemoryProperties
[wsi] Get instance proc: vkEnumerateDeviceExtensionProperties
[wsi] Get instance proc: vkEnumerateDeviceLayerProperties
[wsi] Get instance proc: vkGetPhysicalDeviceSparseImageFormatProperties
[wsi] Get instance proc: vkEnumeratePhysicalDeviceGroups
[wsi] Get instance proc: vkGetPhysicalDeviceFeatures2
[wsi] Get instance proc: vkGetPhysicalDeviceProperties2
[wsi] Get instance proc: vkGetPhysicalDeviceFormatProperties2
[wsi] Get instance proc: vkGetPhysicalDeviceImageFormatProperties2
[wsi] Get instance proc: vkGetPhysicalDeviceQueueFamilyProperties2
[wsi] Get instance proc: vkGetPhysicalDeviceMemoryProperties2
[wsi] Get instance proc: vkGetPhysicalDeviceSparseImageFormatProperties2
[wsi] Get instance proc: vkGetPhysicalDeviceExternalBufferProperties
[wsi] Get instance proc: vkGetPhysicalDeviceExternalFenceProperties
[wsi] Get instance proc: vkGetPhysicalDeviceExternalSemaphoreProperties
[wsi] Get instance proc: vkGetPhysicalDeviceToolProperties
[wsi] Get instance proc: vkDestroySurfaceKHR
[wsi] Get instance proc: vkGetPhysicalDeviceSurfaceSupportKHR
[wsi] Get instance proc: vkGetPhysicalDeviceSurfaceCapabilitiesKHR
[wsi] Get instance proc: vkGetPhysicalDeviceSurfaceFormatsKHR
[wsi] Get instance proc: vkGetPhysicalDeviceSurfacePresentModesKHR
[wsi] Get instance proc: vkGetPhysicalDevicePresentRectanglesKHR
[wsi] Get instance proc: vkGetPhysicalDeviceDisplayPropertiesKHR
[wsi] Get instance proc: vkGetPhysicalDeviceDisplayPlanePropertiesKHR
[wsi] Get instance proc: vkGetDisplayPlaneSupportedDisplaysKHR
[wsi] Get instance proc: vkGetDisplayModePropertiesKHR
[wsi] Get instance proc: vkCreateDisplayModeKHR
[wsi] Get instance proc: vkGetDisplayPlaneCapabilitiesKHR
[wsi] Get instance proc: vkCreateDisplayPlaneSurfaceKHR
[wsi] Get instance proc: vkCreateXlibSurfaceKHR
[wsi] Get instance proc: vkGetPhysicalDeviceXlibPresentationSupportKHR
[wsi] Get instance proc: vkCreateXcbSurfaceKHR
[wsi] Get instance proc: vkGetPhysicalDeviceXcbPresentationSupportKHR
[wsi] Get instance proc: vkCreateWaylandSurfaceKHR
[wsi] Get instance proc: vkGetPhysicalDeviceWaylandPresentationSupportKHR
[wsi] Get instance proc: vkGetPhysicalDeviceVideoCapabilitiesKHR
[wsi] Get instance proc: vkGetPhysicalDeviceVideoFormatPropertiesKHR
[wsi] Get instance proc: vkGetPhysicalDeviceFeatures2KHR
[wsi] Get instance proc: vkGetPhysicalDeviceProperties2KHR
[wsi] Get instance proc: vkGetPhysicalDeviceFormatProperties2KHR
[wsi] Get instance proc: vkGetPhysicalDeviceImageFormatProperties2KHR
[wsi] Get instance proc: vkGetPhysicalDeviceQueueFamilyProperties2KHR
[wsi] Get instance proc: vkGetPhysicalDeviceMemoryProperties2KHR
[wsi] Get instance proc: vkGetPhysicalDeviceSparseImageFormatProperties2KHR
[wsi] Get instance proc: vkEnumeratePhysicalDeviceGroupsKHR
[wsi] Get instance proc: vkGetPhysicalDeviceExternalBufferPropertiesKHR
[wsi] Get instance proc: vkGetPhysicalDeviceExternalSemaphorePropertiesKHR
[wsi] Get instance proc: vkGetPhysicalDeviceExternalFencePropertiesKHR
[wsi] Get instance proc: vkEnumeratePhysicalDeviceQueueFamilyPerformanceQueryCountersKHR
[wsi] Get instance proc: vkGetPhysicalDeviceQueueFamilyPerformanceQueryPassesKHR
[wsi] Get instance proc: vkGetPhysicalDeviceSurfaceCapabilities2KHR
[wsi] Get instance proc: vkGetPhysicalDeviceSurfaceFormats2KHR
[wsi] Get instance proc: vkGetPhysicalDeviceDisplayProperties2KHR
[wsi] Get instance proc: vkGetPhysicalDeviceDisplayPlaneProperties2KHR
[wsi] Get instance proc: vkGetDisplayModeProperties2KHR
[wsi] Get instance proc: vkGetDisplayPlaneCapabilities2KHR
[wsi] Get instance proc: vkGetPhysicalDeviceFragmentShadingRatesKHR
[wsi] Get instance proc: vkGetPhysicalDeviceVideoEncodeQualityLevelPropertiesKHR
[wsi] Get instance proc: vkGetPhysicalDeviceCooperativeMatrixPropertiesKHR
[wsi] Get instance proc: vkGetPhysicalDeviceCalibrateableTimeDomainsKHR
[wsi] Get instance proc: vkCreateDebugReportCallbackEXT
[wsi] Get instance proc: vkDestroyDebugReportCallbackEXT
[wsi] Get instance proc: vkDebugReportMessageEXT
[wsi] Get instance proc: vkGetPhysicalDeviceExternalImageFormatPropertiesNV
[wsi] Get instance proc: vkReleaseDisplayEXT
[wsi] Get instance proc: vkAcquireXlibDisplayEXT
[wsi] Get instance proc: vkGetRandROutputDisplayEXT
[wsi] Get instance proc: vkGetPhysicalDeviceSurfaceCapabilities2EXT
[wsi] Get instance proc: vkCreateDebugUtilsMessengerEXT
[wsi] Get instance proc: vkDestroyDebugUtilsMessengerEXT
[wsi] Get instance proc: vkSubmitDebugUtilsMessageEXT
[wsi] Get instance proc: vkGetPhysicalDeviceMultisamplePropertiesEXT
[wsi] Get instance proc: vkGetPhysicalDeviceCalibrateableTimeDomainsEXT
[wsi] Get instance proc: vkGetPhysicalDeviceToolPropertiesEXT
[wsi] Get instance proc: vkGetPhysicalDeviceCooperativeMatrixPropertiesNV
[wsi] Get instance proc: vkGetPhysicalDeviceSupportedFramebufferMixedSamplesCombinationsNV
[wsi] Get instance proc: vkCreateHeadlessSurfaceEXT
[wsi] Get instance proc: vkAcquireDrmDisplayEXT
[wsi] Get instance proc: vkGetDrmDisplayEXT
[wsi] Get instance proc: vkGetPhysicalDeviceOpticalFlowImageFormatsNV
Selected GPU 0: AMD Radeon RX 6700 XT (RADV NAVI22), type: DiscreteGpu
[wsi] Get instance proc: vkCreateDevice
thread '<unnamed>' panicked at wsi/src/storage.rs:93:13:
Can't retrieve value when storage was not initialized!
stack backtrace:
   0:     0x7efcf00aae5c - std::backtrace_rs::backtrace::libunwind::trace::ha69d38c49f1bf263
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x7efcf00aae5c - std::backtrace_rs::backtrace::trace_unsynchronized::h93125d0b85fd543c
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7efcf00aae5c - std::sys_common::backtrace::_print_fmt::h8d65f438e8343444
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x7efcf00aae5c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h41751d2af6c8033a
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x7efcf00ca52c - core::fmt::rt::Argument::fmt::h5db2f552d8a28f63
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/core/src/fmt/rt.rs:138:9
   5:     0x7efcf00ca52c - core::fmt::write::h99465148a27e4883
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/core/src/fmt/mod.rs:1114:21
   6:     0x7efcf00a8c0e - std::io::Write::write_fmt::hee8dfd57bd179ab2
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/io/mod.rs:1763:15
   7:     0x7efcf00aac44 - std::sys_common::backtrace::_print::h019a3cee3e814da4
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x7efcf00aac44 - std::sys_common::backtrace::print::h55694121c2ddf918
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x7efcf00ac043 - std::panicking::default_hook::{{closure}}::h29cbe3da3891b0b0
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/panicking.rs:272:22
  10:     0x7efcf00abd64 - std::panicking::default_hook::h881e76b2b8c74280
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/panicking.rs:292:9
  11:     0x7efcf00ac5c5 - std::panicking::rust_panic_with_hook::hcc36e25b6e33969c
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/panicking.rs:731:13
  12:     0x7efcf00ac476 - std::panicking::begin_panic_handler::{{closure}}::ha415efb0f69f41f9
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/panicking.rs:601:13
  13:     0x7efcf00ab386 - std::sys_common::backtrace::__rust_end_short_backtrace::h395fe90f99451e4e
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/sys_common/backtrace.rs:170:18
  14:     0x7efcf00ac212 - rust_begin_unwind
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/panicking.rs:597:5
  15:     0x7efcf007cd05 - core::panicking::panic_fmt::h452a83e54ecd764e
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/core/src/panicking.rs:72:14
  16:     0x7efcf008c0e9 - wsi::storage::Storage<K,V>::get::h9b7da83f16cffa2b
                               at /home/nadeem/Repos/vulkan-layer-rs/wsi/src/storage.rs:93:13
  17:     0x7efcf008c565 - wsi::storage::Storage<K,V>::read::hdad07a1509fb75f7
                               at /home/nadeem/Repos/vulkan-layer-rs/wsi/src/storage.rs:118:32
  18:     0x7efcf0087437 - wsi::layer::private::DeviceData::read::h9216222fc52434c8
                               at /home/nadeem/Repos/vulkan-layer-rs/wsi/src/layer/private.rs:63:9
  19:     0x7efcf0086ab8 - wsi_layer_GetDeviceProcAddr
                               at /home/nadeem/Repos/vulkan-layer-rs/wsi/src/layer/mod.rs:85:37
  20:     0x7efcefef9562 - <unknown>
  21:     0x7efcefef4e3b - <unknown>
  22:     0x7efceff05cbb - vkCreateDevice
  23:     0x55b3ffbc8791 - <unknown>
  24:     0x7efcefceccd0 - <unknown>
  25:     0x7efcefcecd8a - __libc_start_main
  26:     0x55b3ffbca7c5 - <unknown>
  27:                0x0 - <unknown>
fatal runtime error: failed to initiate panic, error 5
Aborted (core dumped)
```

**Comment by NadeemSadiq** [comment]
To add a little bit more to this. It seems like when it hits the `vkGetDeviceQueue` the device storage is no longer there for what ever reason. Will continue to see why this is happening.

EDIT: I wonder if this issue is related to the fact that the `vkCreateDevice` gets routed without going through the layer. Will do some test and see if this is the case

**Comment by NadeemSadiq** [comment]
Found the issue. Will push a PR for this

**Comment by NadeemSadiq** [comment]
I am a little new to github so I am not sure if i can't do this due to permissions on the repo level or what but I am unable to push my branch with the fixes. Here is my git diff just in case you want it. Will close this issue since this changes i made below has fixed this for me

```
diff --git a/wsi/build.rs b/wsi/build.rs
index 8fcc7ba..32171f8 100644
--- a/wsi/build.rs
+++ b/wsi/build.rs
@@ -22,20 +22,26 @@ fn main() {
     };
 
     let json = format!(
-        "{{ \
-  \"file_format_version\" : \"1.0.0\", \
-  \"layer\" : {{ \
-    \"name\": \"VK_LAYER_{}\", \
-    \"type\": \"GLOBAL\", \
-    \"library_path\": \"{}\", \
-    \"api_version\": \"{}\", \
-    \"implementation_version\": \"1\", \
-    \"description\": \"Sample layer - https://renderdoc.org/vulkan-layer-guide.html\", \
-    \"functions\": {{ \
-      \"vkGetInstanceProcAddr\": \"wsi_layer_GetInstanceProcAddr\", \
-      \"vkGetDeviceProcAddr\": \"wsi_layer_GetDeviceProcAddr\" \
-    }} \
-  }} \
+        "{{ 
+  \"file_format_version\" : \"1.0.0\", 
+  \"layer\" : {{ 
+    \"name\": \"VK_LAYER_{}\", 
+    \"type\": \"GLOBAL\", 
+    \"library_path\": \"{}\", 
+    \"api_version\": \"{}\", 
+    \"implementation_version\": \"1\", 
+    \"description\": \"Sample layer - https://renderdoc.org/vulkan-layer-guide.html\", 
+    \"functions\": {{ 
+      \"vkGetInstanceProcAddr\": \"wsi_layer_GetInstanceProcAddr\", 
+      \"vkGetDeviceProcAddr\": \"wsi_layer_GetDeviceProcAddr\" 
+    }}, 
+    \"enable_environment\": {{
+      \"ENABLE_SAMPLE_LAYER\": \"1\"
+    }},
+    \"disable_environment\": {{
+      \"DISABLE_SAMPLE_LAYER\": \"1\"
+    }}
+  }} 
 }}",
         name, link_name, api_version
     );
diff --git a/wsi/src/layer/mod.rs b/wsi/src/layer/mod.rs
index 6078c33..c020a52 100644
--- a/wsi/src/layer/mod.rs
+++ b/wsi/src/layer/mod.rs
@@ -54,6 +54,7 @@ pub extern "system" fn wsi_layer_GetInstanceProcAddr(
         },
         "vkCreateInstance" => unsafe { mem::transmute(wsi_layer_vkCreateInstance as *const ()) },
         "vkDestroyInstance" => unsafe { mem::transmute(wsi_layer_vkDestroyInstance as *const ()) },
+        "vkCreateDevice" => unsafe { mem::transmute(wsi_layer_vkCreateDevice as *const ()) },
         _ => {
             let instance_data_guard = InstanceData::read(&instance);
             // If the function is not intercepted by our layer we simply forward the call to the next
```

**Comment by exellian** [comment]
Good catch! Yes the createDevice function was probably missing in GetInstanceProcAddr. The example is very simple at the moment and probably also some other functions are missing. But thanks for the investigation! On github you could fork this repository, push your changes to your own version of this repository and then create a pull request to merge it back to this repo.
